<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Models\Fornecedor;
use Faker\Generator as Faker;

$factory->define(Fornecedor::class, function (Faker $faker) {

    return [
        'for_admin_id' => $faker->randomDigitNotNull,
        'for_razao' => $faker->word,
        'for_contexto' => $faker->word,
        'for_qualvalor' => $faker->randomDigitNotNull,
        'for_cnpj' => $faker->word,
        'for_inscrest' => $faker->word,
        'for_fantasia' => $faker->word,
        'for_rua' => $faker->word,
        'for_complem' => $faker->word,
        'for_bairro' => $faker->word,
        'for_cidade' => $faker->word,
        'for_estado' => $faker->word,
        'for_cep' => $faker->randomDigitNotNull,
        'for_email' => $faker->word,
        'for_banco' => $faker->randomDigitNotNull,
        'for_agencia' => $faker->word,
        'for_conta' => $faker->word,
        'for_saldo' => $faker->randomDigitNotNull,
        'for_login' => $faker->word,
        'for_senha' => $faker->word,
        'for_mudasenha' => $faker->word,
        'for_telefone1' => $faker->word,
        'for_telefone2' => $faker->word,
        'for_celular' => $faker->word,
        'for_status' => $faker->word,
        'for_data' => $faker->word,
        'for_basedolar' => $faker->randomDigitNotNull,
        'for_contato' => $faker->word,
        'for_saldoreal' => $faker->randomDigitNotNull,
        'for_fundador' => $faker->word,
        'for_comddi' => $faker->word,
        'for_dia_vencimento' => $faker->word,
        'for_contas_voip' => $faker->randomDigitNotNull,
        'for_valor_billing' => $faker->randomDigitNotNull,
        'for_tempo_ligacao' => $faker->randomDigitNotNull,
        'for_inicio_internacionais' => $faker->word,
        'for_inicio_nacionais' => $faker->word,
        'for_podemudarvlrs' => $faker->word,
        'for_finalizar_ligacao' => $faker->word,
        'for_sgs_comecar_cobrar' => $faker->randomDigitNotNull,
        'for_contas_gvt' => $faker->randomDigitNotNull,
        'for_mostrarassinonline' => $faker->word,
        'for_logo_master' => $faker->word,
        'for_especial' => $faker->word,
        'for_qtd_digitos_minimo' => $faker->randomDigitNotNull,
        'for_reinvite' => $faker->word,
        'for_prefvoipvoip' => $faker->word,
        'for_ringfalso' => $faker->word,
        'for_linguagem' => $faker->word,
        'for_ultimoconsumo' => $faker->randomDigitNotNull,
        'for_podeprocessar' => $faker->word,
        'for_senhaadmin' => $faker->word,
        'for_abrirwebphone' => $faker->word,
        'for_brpay' => $faker->word,
        'for_tempo_ligacao_cel' => $faker->randomDigitNotNull,
        'for_usar_4003' => $faker->word,
        'for_voiptovoip_semcredito' => $faker->word,
        'for_darmensagemsemcredito' => $faker->word,
        'for_sgs_comecar_cobrar_celular' => $faker->randomDigitNotNull,
        'for_mostrar_ligacoes_nao_cobradas' => $faker->word,
        'for_plataforma_exclusiva' => $faker->word,
        'for_limitar_digitos_ligacao' => $faker->word,
        'for_saldo4003' => $faker->randomDigitNotNull,
        'for_atualizado' => $faker->word,
        'for_venda_4003' => $faker->randomDigitNotNull,
        'for_terminacao_automatica' => $faker->word,
        'for_venda_0800_fixo' => $faker->randomDigitNotNull,
        'for_venda_0800_celular' => $faker->randomDigitNotNull,
        'for_socobrar_4003_secompletar' => $faker->word,
        'for_cobrar_4003_emumatarifaso' => $faker->word,
        'for_tipo_lig_permitidas_4003' => $faker->word,
        'for_tp_tarifacao_4003' => $faker->word,
        'for_tempo_dial_voip' => $faker->randomDigitNotNull,
        'for_tempo_dial_pstn' => $faker->randomDigitNotNull,
        'for_rechamar_congestion' => $faker->word,
        'for_rechamar_chanunavail' => $faker->word,
        'for_rechamar_noanswer' => $faker->word,
        'for_rechamar_busy' => $faker->word,
        'for_venda_sms' => $faker->randomDigitNotNull,
        'for_saldosms' => $faker->randomDigitNotNull,
        'for_valor_dolar_hoje' => $faker->randomDigitNotNull,
        'for_gravar_ligacoes' => $faker->word,
        'for_saldo0800cartoes' => $faker->randomDigitNotNull,
        'for_limite_lig_simultaneas' => $faker->randomDigitNotNull,
        'for_dar_mensagem_numerica' => $faker->word,
        'for_prefixo_fax' => $faker->word,
        'for_sms_provedor_proprio' => $faker->word,
        'for_end_url_provedor_sms' => $faker->word,
        'for_login_provedor_sms' => $faker->word,
        'for_senha_provedor_sms' => $faker->word,
        'for_texto_ddi_sms' => $faker->word,
        'for_banco2' => $faker->randomDigitNotNull,
        'for_agencia2' => $faker->word,
        'for_conta2' => $faker->word,
        'for_banco3' => $faker->randomDigitNotNull,
        'for_agencia3' => $faker->word,
        'for_conta3' => $faker->word,
        'for_usar_portabilidade' => $faker->word,
        'for_provedor_portabilidade' => $faker->randomDigitNotNull,
        'for_portabilidade_senha' => $faker->word
    ];
});
