<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Models\Representante;
use Faker\Generator as Faker;

$factory->define(Representante::class, function (Faker $faker) {

    return [
        'rep_fornecedor_id' => $faker->randomDigitNotNull,
        'rep_razao' => $faker->word,
        'rep_documento' => $faker->word,
        'rep_inscrest' => $faker->word,
        'rep_fantasia' => $faker->word,
        'rep_rua' => $faker->word,
        'rep_complem' => $faker->word,
        'rep_bairro' => $faker->word,
        'rep_cidade' => $faker->word,
        'rep_estado' => $faker->word,
        'rep_cep' => $faker->randomDigitNotNull,
        'rep_email' => $faker->word,
        'rep_banco' => $faker->randomDigitNotNull,
        'rep_agencia' => $faker->word,
        'rep_conta' => $faker->word,
        'rep_saldo' => $faker->randomDigitNotNull,
        'rep_login' => $faker->word,
        'rep_senha' => $faker->word,
        'rep_mudasenha' => $faker->word,
        'rep_telefone1' => $faker->word,
        'rep_telefone2' => $faker->word,
        'rep_celular' => $faker->word,
        'rep_status' => $faker->word,
        'rep_perccomissao' => $faker->randomDigitNotNull,
        'rep_data' => $faker->word,
        'rep_contato' => $faker->word,
        'rep_percacrescimo' => $faker->randomDigitNotNull,
        'rep_saldoreal' => $faker->randomDigitNotNull,
        'rep_nomebanco' => $faker->word,
        'rep_tpconta' => $faker->word,
        'rep_nomebanco2' => $faker->word,
        'rep_tpconta2' => $faker->word,
        'rep_banco2' => $faker->randomDigitNotNull,
        'rep_agencia2' => $faker->word,
        'rep_conta2' => $faker->word,
        'rep_nomebanco3' => $faker->word,
        'rep_tpconta3' => $faker->word,
        'rep_banco3' => $faker->randomDigitNotNull,
        'rep_agencia3' => $faker->word,
        'rep_conta3' => $faker->word,
        'rep_tptarifa' => $faker->word,
        'rep_usarpospago' => $faker->word,
        'rep_atualizado' => $faker->word,
        'rep_criarcontas' => $faker->word,
        'rep_terminacao_id' => $faker->randomDigitNotNull,
        'rep_terminacao2_id' => $faker->randomDigitNotNull,
        'rep_terminacao3_id' => $faker->randomDigitNotNull,
        'rep_terminacao_cel_id' => $faker->randomDigitNotNull,
        'rep_terminacao2_cel_id' => $faker->randomDigitNotNull,
        'rep_terminacao3_cel_id' => $faker->randomDigitNotNull,
        'rep_terminacao_int_id' => $faker->randomDigitNotNull,
        'rep_terminacao2_int_id' => $faker->randomDigitNotNull,
        'rep_terminacao3_int_id' => $faker->randomDigitNotNull,
        'rep_cobrar_voipvoip' => $faker->word,
        'rep_linguagem' => $faker->word,
        'rep_tabelaespecial_id' => $faker->randomDigitNotNull,
        'rep_lig_simultaneas' => $faker->randomDigitNotNull,
        'rep_vlrporconta' => $faker->randomDigitNotNull,
        'rep_diacobranca' => $faker->randomDigitNotNull,
        'rep_sgs_comecar_cobrar' => $faker->randomDigitNotNull,
        'rep_usa_cabines' => $faker->word,
        'rep_avisar_fimcreditos' => $faker->word,
        'rep_vlrmin_avisar' => $faker->randomDigitNotNull,
        'rep_sgs_comecar_cobrar_celular' => $faker->randomDigitNotNull,
        'rep_usa_4003' => $faker->word,
        'rep_venda_4003' => $faker->randomDigitNotNull,
        'rep_venda_0800_fixo' => $faker->randomDigitNotNull,
        'rep_venda_0800_celular' => $faker->randomDigitNotNull,
        'rep_socobrar_4003_secompletar' => $faker->word,
        'rep_cobrar_4003_emumatarifaso' => $faker->word,
        'rep_tipo_lig_permitidas_4003' => $faker->word,
        'rep_tp_tarifacao_4003' => $faker->word,
        'rep_usa_sms' => $faker->word,
        'rep_venda_sms' => $faker->randomDigitNotNull,
        'rep_vlr_min_voip2voip' => $faker->randomDigitNotNull,
        'rep_limite_lig_simultaneas' => $faker->randomDigitNotNull,
        'rep_ficar_negativo' => $faker->word,
        'rep_limite_ficar_negativo' => $faker->randomDigitNotNull,
        'rep_assinante_cartoes' => $faker->word,
        'rep_logo_revenda' => $faker->word,
        'rep_gravar_chamadas' => $faker->word,
        'rep_falar_codigo_erros' => $faker->word,
        'rep_host_smtp' => $faker->word,
        'rep_cripto_smtp' => $faker->word,
        'rep_port_smtp' => $faker->randomDigitNotNull,
        'rep_usuario_smtp' => $faker->word,
        'rep_password_smtp' => $faker->word,
        'rep_vlr_minimo_credito' => $faker->randomDigitNotNull,
        'rep_recibo_deposito_obrigatorio' => $faker->word
    ];
});
